export enum PostsActionType {
    FETCH_POSTS = 'POSTS_FETCH_POSTS',
    START_CREATING_NEW_POST = 'POSTS_START_CREATING_NEW_POST',
    CANCEL_CREATING_NEW_POST = 'POSTS_CANCEL_CREATING_NEW_POST',
    SUBMIT_NEW_POST = 'POSTS_SUBMIT_NEW_POST',
}
