export enum UserActionType {
    SIGN_IN = 'USER_SIGNIN',
    SIGN_OUT = 'USER_SIGNOUT',
    GET_SESSION = 'USER_GET_SESSION',
    FETCH_MY_USER_DATA = 'FETCH_MY_USER_DATA',
    SET_AUTHENTICATING = 'USER_SET_AUTHENTICATING',
    SET_AUTH_MESSAGE = 'USER_SET_AUTH_MESSAGE',
    UNSET_AUTH_MESSAGE = 'USER_UNSET_AUTH_MESSAGE',
}
